version: "3.9"

services:
  server:
    build: .
    container_name: paseto-server
    ports:
      - "8181:8181"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/pengujiantoken
      - PORT=8181
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    stdin_open: true
    command: npm run pasetomongoserver
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2048M

  authserver:
    build: .
    container_name: paseto-authserver
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/pengujiantoken
      - PORT=8080
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    stdin_open: true
    command: npm run pasetomongoauth
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2048M

volumes:
  node_modules:
