GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRpdmEiLCJpYXQiOjE2NzEwMjY2OTAsImV4cCI6MTY3MTAyNjcyMH0.43ISbdY6-WOp-EnBhi_iPgDVoCeJUbVRXjZB8ekCTtWr6-G9y5J6TLTCCmnzfang

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRpdmEiLCJpYXQiOjE2NzcxNjE3MDd9.5EIR0k9Bq190syZPHmw5n8tDJmsuOkQrVWL8PoOWo7U"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRpdmEiLCJpYXQiOjE2NzcxNjY2OTh9.P5v6RwbcufzZn9reukQOsMGr8AwzNUJtfF1Y7pfQNEM"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "adiva",
    "password" : "adiva"
}