GET http://localhost:8181/posts
Authorization: Bearer v3.local.iHIARatXujd4Vd4Qv9ZwYGte5ja2do5XOIr8JgiejozKczpW6KP11PNpaFgADOdXU-tulCV9AHBUV7B_ejn9h68542wPk4iXvEZgCPzoRf953tWaERDIWruU7HEOcIqNaU49KF6QiHRvCIC6JM9KkZ6DmgXsvq_YxGaPVpS4PIFnGGRO28GyGazepo995vbzPcubZXgACOOyZ-uEIqflLE7xtLJGeuA5K7i4dHm_mxj6c8Wq0x0wtl228Bl7dbAdNNcroOSFTeByPT3Moo-mrNE8wOvi8p7vseHMqw

###
DELETE http://localhost:8080/logout
Content-Type: application/json

{
    "token" : "v3.local.wbKo-aTkgOzdFrYHwgK-W9iPq2K5u_3xdG19CEEu-ZHc69yh_I7_Ycpa8ST4BJ4F80SC7jG4ZqAXqXJnbTvr9HBp8CPj0Pt2XdM2KxrPbfOiFo3CVoKoCObES2b9c_FlX7OOUJ1-98CHAfjsy_79Q3Dxz9TAQX3lI1fj8AS3-IKn"
}

###
POST http://localhost:8080/token
Content-Type: application/json

{
    "token": "v3.local.F9q7iWbB9h2z9QCtOTIf85vlbcWmFqWp58VVJnbMeAi0T6BsfGLYNMvnzuHe1lm_Fqgtiu9CV0bPQXc56ti1Efh4c1swWJGNjwsMEoYB78eumex-3e1gu0gtt2XlZ8uyw56HE2QUW8b4jpPHBLb5aw9I_pPU2A3eHGMeSwQ5d2z0"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "admin"
}