GET http://localhost:8181/posts
Authorization: Bearer v3.local.kIrwN2NzCfcZmYC37UhSNf289OMFB0cTQBIT1_RLxr5uO0Wk5WP6xfIxpegQQHrm-Xr84AYWsWSB76-_O9zyZP_oen8g-jgKBkeJvN9QQXmYLxM3zTRRb37OwxWH6AhzBoIbhLTqr1m3mzzuDDex3dyffSs8mwvuoPlBJvdXSCLUNS9QXvtzwKbDxF1Xgg0CXKXfhZ_ZV4y4Qx-2yMKAOjLds3l5ukYwb1KxVa5DNTUoFQWdsI6SxlFxj6Xi9ByPKrbl4wXPJAaCBMm9hrIrWFDGu1q574TTgqM5zA

###
DELETE http://localhost:8080/logout
Content-Type: application/json

{
    "token" : "v3.local.wbKo-aTkgOzdFrYHwgK-W9iPq2K5u_3xdG19CEEu-ZHc69yh_I7_Ycpa8ST4BJ4F80SC7jG4ZqAXqXJnbTvr9HBp8CPj0Pt2XdM2KxrPbfOiFo3CVoKoCObES2b9c_FlX7OOUJ1-98CHAfjsy_79Q3Dxz9TAQX3lI1fj8AS3-IKn"
}

###
POST http://localhost:8080/token
Content-Type: application/json

{
    "token": "v3.local.6P8SaGJNaS5RGTKG3MYsFfCsC5x61jgDpoWiAYNEkFP91c-3XXG6epjZLImm4lblHqCVc9mOYMCzEmO1Te5veMa9AGcYT4GWUQ8J2cs_2oY3iyVRexxw48Q5ZzvHxkDr91ApjdnaP0nLcU0sodpVHNqwVKIHTO1gu9s8B7E9XGzm"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "admin"
}