GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRpdmEiLCJpYXQiOjE2Nzc1OTQwOTksImV4cCI6MTY3NzU5NDEyOX0._CAXoiSPlg73ADC-mMhUsP60lT7F9ewhd7CaLUIk6HvPsuayuVC0z5bqZWPg_9mP

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRpdmEiLCJpYXQiOjE2Nzc1OTM3NDd9.nAGNUqYCzjjL7oF6toLV4PK6f9DyFm8SlMIAaMo6Eb8"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRpdmEiLCJpYXQiOjE2Nzc1OTM3NDd9.nAGNUqYCzjjL7oF6toLV4PK6f9DyFm8SlMIAaMo6Eb8"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "adiva",
    "password" : "adiva"
}