version: "3.9"

services:
  server:
    build: .
    container_name: server
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/pengujiantoken
      - PORT=3000
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    stdin_open: true
    command: npm run devStart
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2048M

  authserver:
    build: .
    container_name: authserver
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/pengujiantoken
      - PORT=3000
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    stdin_open: true
    command: npm run devStart2
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2048M

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=pengujiantoken
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  node_modules:
