version: "3.9"

services:
  algnone:
    build: .
    container_name: algnone
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/skenario_dua
      - PORT=3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    stdin_open: true
    command: npm run ajwt
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2048M

volumes:
  node_modules:
