###
GET http://localhost:3000/verify
Authorization: Bearer eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJ1c2VySWQiOiIzIiwibmFtZSI6ImJvYiIsImlhdCI6MTY4MDIzMzE2Nn0.

### LOGIN
POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "alice",
    "password" : "alice"
}

###
POST http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJ1c2VySWQiOiIyIiwibmFtZSI6ImFsaWNlIiwiZW1haWwiOiJhbGljZUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MDI0Mzc4MX0.
Content-Type: application/json

{
    "username" : "testing",
    "email" : "email@testing.com",
    "password" : "testing",
    "role" : "admin"
}