###
GET http://localhost:3000/verify
Authorization: Bearer eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJ1c2VySWQiOiIzIiwibmFtZSI6ImJvYiIsImlhdCI6MTY4MDIzMzE2Nn0.

### LOGIN
POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "alice",
    "password" : "alice"
}

###
POST http://localhost:3000/api/users
Authorization: Bearer eyAiYWxnIjoibm9uZSIsICJ0eXAiOiJKV1QifQ.eyJ1c2VySWQiOiAiMyIsIm5hbWUiOiAiYm9iIiwiZW1haWwiOiAiYm9iQGV4YW1wbGUuY29tIiwicm9sZSI6ICJhZG1pbiIsICJpYXQiOiAxNjgwNzA2NzIzLCAiaXNzIjogInVybjpqd3QifQ.
Content-Type: application/json

{
    "username" : "hacking",
    "email" : "email@hacking.com",
    "password" : "hacking",
    "role" : "admin"
}



################# PASETO ###########################

### LOGIN
POST http://localhost:8080/login
Content-Type: application/json

{
    "username" : "bob",
    "password" : "bob"
}