### ===================== 1A ============================
### === Skenario 1A PASETO Akses API secara tidak sah ===
### 1. LOGIN
POST http://localhost:8080/login
Content-Type: application/json

{
    "username" : "bob",
    "password" : "bob"
}
### 2. Respons server akses secara sah (Bob dengan shopid 1 = sah)
GET  http://localhost:8080/shops/1/revenue_data.json
Authorization: Bearer v3.local.1c49GX7Tt7QjNObIIjeTwoLjKD3tz7N6DtKBTtu5fFhi5k9cOqPrwzp34IEOYs6rDez9qtKouBtNAvEHTfxfCLiVO0INt_BqL77Wvd3gnAgjb8RHBAN03qwqgJb8s9zegdIsuu2wkbZYOCxO-_d02vlU071vafhCwjRjW0_0lt-_4XPMgJDUaRaZUg4BKf2ODQV9f9EmDW30nr0ihOQ_J8mQjIf1eNlhy2wwsgeukmUfsYH55LpqQ4ZEBI9DlF6l80SuYrWZze3T0LpAQi0geBffUjHWcwG1PJNkLkQSM8rD

### === Skenario 1A PASETO Akses API secara tidak sah ===
GET  http://localhost:8080/shops/2/revenue_data.json
Authorization: Bearer v3.local.1c49GX7Tt7QjNObIIjeTwoLjKD3tz7N6DtKBTtu5fFhi5k9cOqPrwzp34IEOYs6rDez9qtKouBtNAvEHTfxfCLiVO0INt_BqL77Wvd3gnAgjb8RHBAN03qwqgJb8s9zegdIsuu2wkbZYOCxO-_d02vlU071vafhCwjRjW0_0lt-_4XPMgJDUaRaZUg4BKf2ODQV9f9EmDW30nr0ihOQ_J8mQjIf1eNlhy2wwsgeukmUfsYH55LpqQ4ZEBI9DlF6l80SuYrWZze3T0LpAQi0geBffUjHWcwG1PJNkLkQSM8rD

# ================ 1B =========================
## === Skenario 1B PASETO PATCH X-User-Id (UPDATE USER sesuai dengan IDnya) ===
### 1. LOGIN
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "username" : "john",
    "password" : "john"
}
### 2. Mencoba mengganti username dan password 
PATCH  http://localhost:8080/users/1
Authorization: Bearer v3.local.CVMrQmS7TzZqB5aOH8LeAzGh6besjFFniIo4y6du_nvjqWXnmoh6aqFqOxxptfx8KnwZyjaAUNvOcUxo6Pux78SSKZufjtAXnGCuDjXDgkaYtAr6Z0CcuCrGOC337P_KyqxQO7nJLfNMDR06GdvgBvizf4gLxkHzvbJles5XOgqd94TyX27QdS-_Onn2uOwiadkptjH6Qi5MKEIUHLuCyvoQ-JtsbNrJyuE95pZZW2GXQZIU7khTntaA7BezOcVlCJoRiycGDoqbi6LNaLZJxZFV0-l75mv44g5qv840Hd45dnvoT5OcjA6TyA_8jLfWaNnGpZxFthAkEGG9T4tUd6WTi6JETJjSIS4OQOd3YiSy
Content-Type: application/json

{
    "username" : "john",
    "password" : "john"
}

# ================ LOGOUT DAN REFRESH TOKENS =========================

### LOGOUT
DELETE http://localhost:8080/logout
Content-Type: application/json

{
    "token" : "v3.local.UYN1WM86js6hHmfSYKLbWgEe7Uta180ysKncaqvvpQ4NA7kMLalbyqAkvcrn3juq5fCSk_pEW6uhEcnCh5WvIQQAHBENwfY8gIEwPQbbalpfGMzkbD0cNhiFH5kLfLMrRVWduGxSUBIhMU4IsNkrL2GqOSh3ewTjYMrD7wJNVCiR43F6-UIv_lZgRt-sE_SrUlAsRCz85oaXzqkHU06GIQnLR0zmwGyhbEtmj-FcAA5LUYdsfiU"
}

### REFRESH TOKENS
POST http://localhost:8080/token
Content-Type: application/json

{
    "token": "v3.local.F9q7iWbB9h2z9QCtOTIf85vlbcWmFqWp58VVJnbMeAi0T6BsfGLYNMvnzuHe1lm_Fqgtiu9CV0bPQXc56ti1Efh4c1swWJGNjwsMEoYB78eumex-3e1gu0gtt2XlZ8uyw56HE2QUW8b4jpPHBLb5aw9I_pPU2A3eHGMeSwQ5d2z0"
}