## Skenario 1A Akses API secara sah
### LOGIN
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "username" : "bob",
    "password" : "bob"
}


GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRpdmEiLCJpYXQiOjE2Nzc5MDcxNTUsImV4cCI6MTY3NzkwNzE4NX0.oI6Y3vcZUlZbmibuicIXbeKQL-_2-ADkFFhv3qpFL9tIbMjbGd2czS3N0bxuH3i8

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRpdmEiLCJpYXQiOjE2Nzc5MDcxNTUsImV4cCI6MTY3NzkwNzE4NX0.oI6Y3vcZUlZbmibuicIXbeKQL-_2-ADkFFhv3qpFL9tIbMjbGd2czS3N0bxuH3i8"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRpdmEiLCJpYXQiOjE2Nzc0ODI3MzJ9.30Nj4QyQcDG11XXuL9oInZgfKZaPvCTjHOIoQhglvxk"
}



### Skenario satu A
GET  http://localhost:8080/shops/2/revenue_data.json
Authorization: Bearer v3.local.GmLaI5e1dnBCRRqiPbpz6QK8uQf9dlBUjpRhPvRcwL6XZYMpCqxCy3t5ITGpc1hY730mRpapS99dOazWpKZEuFGPoUKtPpCI913nMrbetO4-lhdM41UvT-LnV5ozcL42ycHNafUSasmm6sT0LfzxgXjbA0DhcHHjp_2mdVVctY4QqJ4nJSiFqXNkwkghRoS-SD9_9G2R5sWD4iGmnvej2ehSKD59qdwu7jbbsq3cc2zmEspV5JBNFhstwy48LGqZiEndbseknAc0qsoFMP6QXvAsQN7YfVkmiKSBTIXmpbE

### Skenario satu B
PATCH  http://localhost:5000/users/2
Authorization: Bearer eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwibmFtZSI6ImhoIiwiZW1haWwiOiJqb2huQGV4YW1wbGUuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODA5MzU0NTQsImV4cCI6MTY4MDkzOTA1NH0.2GajPKKAwt4BnXZwQM5MBjDsvDD1b0R0Yr5VItJqJSYtkXwavv8Lw3dIAd23-5IX
Content-Type: application/json

{
    "username" : "bb",
    "password" : "bb"
}

### VULNERABILITY
GET http://localhost:4000/shops/2/revenue_data.json
