# ================ 1A =========================
## === Skenario 1A JWT Akses API secara sah ===
### 1. LOGIN
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "username" : "bob",
    "password" : "bob"
}

### 2. Respons server akses secara sah (Bob dengan shopid 1 = sah)
GET  http://localhost:5000/shops/1/revenue_data.json
Authorization: Bearer eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzIiwibmFtZSI6ImJvYiIsImVtYWlsIjoiYm9iQGV4YW1wbGUuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODczOTcyNzgsImV4cCI6MTY4NzQwMDg3OH0.qOeo2xrUefFgVj-ZjfVX_K-dHGGnWuZ8r0OKCbW2b-TozAN0lz9IUZ6HKzSnGueB

### === Skenario 1A JWT Akses API secara tidak sah ===
GET  http://localhost:5000/shops/2/revenue_data.json
Authorization: Bearer eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzIiwibmFtZSI6ImJvYiIsImVtYWlsIjoiYm9iQGV4YW1wbGUuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODczOTcyNzgsImV4cCI6MTY4NzQwMDg3OH0.qOeo2xrUefFgVj-ZjfVX_K-dHGGnWuZ8r0OKCbW2b-TozAN0lz9IUZ6HKzSnGueB

# ================ 1B =========================
## === Skenario 1B JWT PATCH X-User-Id (UPDATE USER sesuai dengan IDnya) ===
### 1. LOGIN
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "username" : "adiva",
    "password" : "adiva"
}
### 2. Mencoba mengganti username dan password 
PATCH  http://localhost:5000/users/1
x-User-ID: 
Authorization: Bearer eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwibmFtZSI6ImFkaXZhIiwiZW1haWwiOiJqb2huQGV4YW1wbGUuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODczOTg0OTksImV4cCI6MTY4NzQwMjA5OX0.vKyf6aIMAwHZ4KJJLLUCzCCWlLcv11LbQJ8MyyoyrnYp6GJyvBgocp_bGzcWLYfR
Content-Type: application/json

{
    "username" : "john",
    "password" : "john"
}

# ================ LOGOUT DAN REFRESH TOKENS =========================

### LOGOUT
DELETE http://localhost:5000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRpdmEiLCJpYXQiOjE2Nzc5MDcxNTUsImV4cCI6MTY3NzkwNzE4NX0.oI6Y3vcZUlZbmibuicIXbeKQL-_2-ADkFFhv3qpFL9tIbMjbGd2czS3N0bxuH3i8"
}

### REFRESH TOKENS
POST http://localhost:5000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRpdmEiLCJpYXQiOjE2Nzc0ODI3MzJ9.30Nj4QyQcDG11XXuL9oInZgfKZaPvCTjHOIoQhglvxk"
}






