# ================ 4 =========================
## === Skenario 4 - CSRF ===
### 1. LOGIN
POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "jane",
    "password" : "jane"
}

### 2. Skenario Ganti password dan username
PATCH  http://localhost:3000/users/2
Authorization: Bearer v3.local.D657f4C_O8S_rioPBnapfyARL5EoAK7Uot4EdA_c_nSHjc6zJ-b_sNyRyDNemkgR-T70c42sk9zeXpLZfimn9NayABWm5Zh5H2VqBP-9IxFcyNnRQW5RTsjTW7ImFeFwq-YBM_MB0GdUq1PCy49Hc74odptM0IvgO5UZuLLszhiRBbOfG2pRYn3EBKBY308oCoplWVUuWUvD4lP4gB9NqlqRcubxy3yXAqgYM9eDtwoq56ZejV9uaobdY_YNPHWDcyCjZvtwia9Qz4nYcKBhD6pvYjVKz6LCj6HnoPBcl9Xf-Ojl3tI
Content-Type: application/json

{
    "username" : "adiva",
    "password" : "adiva"
}